version=1.0.2

package.url=https://github.com/CFitz-NSG/NSG-Launcher-Release/releases/download/v1.0.2/NSG-Client-1.0.2.zip
package.sha256=8d119ed5aaadd9ce0dc218c2d09b8bf0d33010b6ee3d5a6298b4e2a26e41dc2b
package.type=zip

launch.file=NSG-Client.jar
launch.javaArgs=-Xmx1024m

backup.enabled=false