version=1.0.1

package.url=https://github.com/CFitz-NSG/NSG-Launcher-Release/releases/download/v1.0.1/NSG-Client-1.0.1.zip
package.sha256=bde3be743536be66d22af7a2f2fb9f6706ba1f7b22c2068e770552f80a3dd616
package.type=zip

launch.file=NSG-Client.jar
launch.javaArgs=-Xmx1024m

backup.enabled=false