version=1.0.0

package.url=https://github.com/Cfitz-NSG/NSG-Launcher-Release/releases/download/v1.0.0/NSG-Client-1.0.0.zip
package.sha256=6da76f981f51530ce593ef68134f949059e5b8815e632b754720472686465342
package.type=zip

launch.file=NSG-Client.jar
launch.javaArgs=-Xmx1024m

backup.enabled=false